#
# Standard Crowbar scenario service template with variable number of controller,
# and compute nodes.
#
# Template parameters:
#   controllers: number of controller nodes (default: 1)
#   computes: number of compute nodes (default: 1)
#
---

service_groups:
  - name: admin
    type: cluster
    prefix: c0
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: 1
    service_components:
      - CLM
  - name: controller
    type: cluster
    prefix: c1
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-controller"
    member_count: '{{ controllers|default(1) }}'
    service_components:
      - CORE
  - name: compute
    type: resource
    prefix: sles-comp
    heat_flavor_id: "{{ vcloud_flavor_name_prefix }}-compute"
    member_count: '{{ computes|default(1) }}'
    min_count: 0
    service_components:
      - COMPUTE
